### ISSUE TITLE
Structure member types with reference

### ISSUE THREAD

**Issue by SpriteOvO** [Ubpa/UDRefl#12]
Issue example:
```
#include <UDRefl/UDRefl.h>

using namespace Ubpa;
using namespace Ubpa::UDRefl;

struct TestT {
    bool Value;
};

int main()
{
    auto &Refl = ReflMngr::Instance();

    ////////////////////////////////////////////////////////////////////////////////////////////////////
    // case 1
    //

    Ubpa::Type BoolType = Type_of<bool>;

    std::cout << "Bool name: " << BoolType.GetName() << '\n';
    std::cout << "Is it <bool> ? " << std::boolalpha << BoolType.Is<bool>() << "\n\n";

    ////////////////////////////////////////////////////////////////////////////////////////////////////
    // case 2
    //

    Refl.RegisterType<TestT>();
    Refl.AddField<&TestT::Value>("Value");

    TestT Test;
    ObjectView Object{Test};

    Object.ForEachVar(
        [](TypeRef Type, FieldRef Field, ObjectView Obj) {
            std::cout << "Field name: " << Obj.GetType().GetName() << ' ' << Field.name.GetView() << '\n';
            std::cout << "Is it <bool> ? " << std::boolalpha << Obj.GetType().Is<bool>() << "\n\n";
            return true;
        }
    );

    return 0;
}
```

Output:
```
Bool name: uint8
Is it <bool> ? true

Field name: &{uint8} Value
Is it <bool> ? false
```

In older versions (I tested in v0.6.1), the second case always returns `true`.
The behavior in the latest version (v0.8.1) is different from my expected result.

BTW, storing the name of the `bool` as "uint8" is a bit strange to me, can't we just store it as "bool"?

And Happy New Year~ :D

**Comment by Ubpa** [comment]
Because Object's type is TestT& in case 2, so type of its vars is lvalue reference. You can use Type::RemoveCVRef and Type::Is<bool> instead.

For the name of bool, You can use template specialization for Ubpa:: type_name<bool>, and return TSTR("bool") in it. You should do it before include UDRefl.h ( after include UTemplate/ Name.h), maybe I will change it as default in the future.

Happy New Year :)

**Comment by SpriteOvO** [comment]
I don't think users need to care about CVRef **by default**. I can't imagine some examples to refute this idea.

If we make `Type::Is` and `ObjectView::As` ignore CVRef by default, when users need to care about CVRef, they can just call some functions like: `Type::IsConst`, `Type::IsVolatile`, `Type::IsLValueReference`, etc...

Then users will no longer need to manually call `Type::RemoveCVRef` and `ObjectView::RemoveReference` when they want to determine the type of that object each time.

---

And, I think `type_name_XXX` functions could probably be further improved.

We can make a `class` with many `bool` and `enum` members to maintain type traits.

When users need to call functions like `IsEnum`, `IsConst`, `IsReference`, etc., we can quickly return the `bool` value of that trait directly instead of finding a string each time.

And when any of traits change, we set a `bool NameDirty` to `true`. When the library internal code or users need to get the type name, if `NameDirty` is `true`, we make a string based on traits `bool` members on the spot and cache it, if `NameDirty` is `false`, we can just return the cached string.

I think this idea can optimize a lot of performance.

**Comment by Ubpa** [comment]
When you are caring about the type, you need to think it like `<type_traits>`. For example, if you want to know wether a type t is x, you need to use `std::is_same_v<std::remove_cvref_t<t>>`. So I think those APIs are reasonable.
Dynamic type traits is really fast. It's no need to optimize them by extra space, check out type_name_is_lvalue_reference for more details.

**Comment by SpriteOvO** [comment]
@Ubpa I get it, thank you!
