### ISSUE TITLE
隐式类型转换问题

### ISSUE THREAD

**Issue by uikino** [Ubpa/UDRefl#14]
### 1. 隐式转换问题
有如下代码:
例1:
```
struct A {
    Glib::ustring value;
};
// register ....
a.Var("value") = "ABC"; // 赋值失败
a.Var("value") = Glib::ustring("ABC"); // 赋值成功
```
以及UDRefl测试用例```UDRefl_test_21_string```中第28行
```
auto str = Mngr.MakeShared(Type_of<std::string>, TempArgsView{ "hello world" }); // 无效对象 没有GetName空串
auto str = Mngr.MakeShared(Type_of<std::string>, TempArgsView{ std::string("hello world") });// 有效
```
所以我猜测UDRefl对于类型的隐式转换处理稍有不足，建议在存在隐式类型转换调用时给予warning

代码能力不足，给不出建议LOL

**Comment by Ubpa** [comment]
`UDRefl_test_21_string` 测试用例里的是个 bug，目前已修复
UDRefl 隐式转换的条件可查看 `ReflMngr::IsCompatible`，总结就是，当满足引用条件、指针/数组条件或可构造条件时发生类型转换。另外当形参类型为 `ObjectView` 时，可接受一切类型的实参。
`"hello world"` 类型是 `&{const{[8]{int}}}`，而我在 `ReflMngr` 的构造函数中，默认注册了 `std::string` 及其构造函数 `std::string(const char*)`，所以 `MakeShared` 时可以发生数组到指针的转换。
发生隐式类型转换时，目前没有警告。暂时也不会引入警告机制。因为“我们认为这是合理的”，一切都跟使用静态 C++ 一样自然即可。

fd4842a

**Comment by Ubpa** [comment]
`UDRefl_test_21_string` 测试用例里的是个 bug，目前已修复
UDRefl 隐式转换的条件可查看 `ReflMngr::IsCompatible`，总结就是，当满足引用条件、指针/数组条件或可构造条件时发生类型转换。另外当形参类型为 `ObjectView` 时，可接受一切类型的实参。
`"hello world"` 类型是 `&{const{[12]{int8}}}`，而我在 `ReflMngr` 的构造函数中，默认注册了 `std::string` 及其构造函数 `std::string(const char*)`，所以 `MakeShared` 时可以发生数组到指针的转换。
发生隐式类型转换时，目前没有警告。暂时也不会引入警告机制。因为“我们认为这是合理的”，一切都跟使用静态 C++ 一样自然即可。
另外，一切函数调用都可能会失败，失败可通过返回值中的 `Type` 是否有效来判断。(返回值为 `void` 时，`Type` 也是有效的）

f6e12ecb3e0ac5d5b72f189de7da0e26114275c4

**Comment by uikino** [comment]
谢谢。受教了，等下我再提个静态库的新issue。
