### ISSUE TITLE
What are the advantages of UDRefl compared with RTTR and META?

### ISSUE THREAD

**Issue by SpriteOvO** [Ubpa/UDRefl#2]
I found this library from Zhihu, and I saw the author compare this library with RTTR and META there, but it was only a short description.

Would you mind explaining in more detail the differences between them?
I am choosing a reflection library recently, just out of curiosity, no offense.

Thanks in advance.

**Comment by Ubpa** [comment]
UDRefl cover all main features they have.
And UDRefl support some important features which they don't have:
- cross platform type ID and type calculation on the string level (it's really important, this tech is invented by me, without this, lots of designs will be terrible. For example, meta's [type node](https://github.com/skypjack/meta/blob/master/src/meta/meta.hpp#L122) need to log type traits manually, but UDRefl can compute it by name. More importantly, UDRefl can convert type like `remove_reference`/`remove_pointer` dynamically.)
- container (Easily write a serialize code)
- meta function (Pay attention to the difference between RTTR and UDRefl when [outputing](https://github.com/rttrorg/rttr#setget-properties))
- reference (`invoke` without any copy. No need to keep type of arguments and parameters exactly same. UDRefl will convert arguments' type between `T`, `T&`, `const T&`, `T&&`, `const T&&`)
- simple structure (data-driven design).

**Comment by Ubpa** [comment]
Take a look at the version [0.8.0](https://github.com/Ubpa/UDRefl/tree/0.8.0), it's really awesome!

**Comment by SpriteOvO** [comment]
> Take a look at the version [0.8.0](https://github.com/Ubpa/UDRefl/tree/0.8.0), it's really awesome!

@Ubpa Sure, I'll take a look. :)

**Comment by Ubpa** [comment]
> > Take a look at the version [0.8.0](https://github.com/Ubpa/UDRefl/tree/0.8.0), it's really awesome!
> 
> @Ubpa Sure, I'll take a look. :)

I nearly refactoring the whole project.
It is really fast, check out 'Type', 'Is*Compatible' and 'NewArgs Guard' to get the point.
The APIs change a lot. They are super graceful. I delete  several thousand lines of the codes without any feature loss. The library support reference and const more correctly, check out 'Var' and 'Invoke' for more details.
It's so much better than other reflection libraries. They are like toys in front of UDRefl.
It's really awesome!
